dist: trusty
sudo: required
language: cpp

# build only the master branch
branches:
    only:
        - master

git:
  depth: 10

env:
    global:
        # Encrypted environment variables
        # http://docs.travis-ci.com/user/encryption-keys/
        # GH_TOKEN="xxxx", for gkide-robot Github token
        # this is for upload the build log, skipped for pull request
        - secure: "OUDW9dSjFFg8gl/SbABuhKq1FAWL27OESKNqrUdYMTw8A9Yi++lG9wiwkdwbm6aBm0qvSQkh3UJsTUnTDgQH8mpl/OJCi/5yXqaoMftKpv+aAKFCN2JC/zAutBQ3NRU3NSzjlz2MTpEIO3xcrh+yVwkR4VfxFQ8N1zylSP/UMrZP6HsOud6rp8SFnN0sSmu+5HK0OaIXp8T2naIJI/xGhGkcvQJ86h3nGgn5zeATusmI/jyH3vVpCfoAuzW9hopRyWgOdwe8mNo+g2Mf6fgAruyt1z+IXFkBlOi64vqakXy78ngjdOYVCv2vZo+JceiLvbkVP6IYEu7VyuTURArTDMutAMsYiyJEt7iQqQ0PZMMJHgmQ3Gm5bgqz41VUP9rBwKGNQ0lTOBpZHujcftpQQFijNY141W0zbe+ZA/7zkcArWn9mv7ExE9qyYyeBS8NfjxoJ/prS+GbgDEr8VMqk2Kjq6ue0sMybCyeW0BM0uGQrd8gOGbqgz5fI5dFeuYgW1gcmR32NWnpDyhnIo9mhHFW2me5MCK/XyTnYaLmPjW+GjvtHSvnceiMpDpAz58Oeq6oRkRlSAkqlB8DZ8EJZx+VNq6RQyY4WqYXVcA2MjDMu9xl+5uydGoSiC9gS9orQU2qu10TvBjrYWZUAMKZCvqGgIW8OHKrEJ48cZoh1C7E="
        # auto upload build log to 'autodocs/dev/log/...'
        - UPLOAD_BUILD_LOG=ON
        # for build nvim only, skip the Qt5 stuff
        # - BUILD_NVIM_ONLY=ON
        # use shared Qt5 library, if it 'OFF' then use static Qt5
        - USE_SHARED_QT5=ON
        # Directory where third-party dependency sources are downloaded to.
        - DEPS_DOWNLOAD_DIR="${HOME}/gkide-deps"
        # Build directory for dependencies libraries
        - DEPS_BUILD_DIR="${DEPS_DOWNLOAD_DIR}/build"
        # If this file exists, the dependencies libraries cache is valid
        - DEPS_CACHE_MARKER="${DEPS_BUILD_DIR}/.travis_cache_marker"
        # Build directory for GKIDE
        - GKIDE_BUILD_DIR="${TRAVIS_BUILD_DIR}/build"
        # Log directory
        - GKIDE_LOG_DIR="${GKIDE_BUILD_DIR}/log"
        # Install directory for gkide
        - GKIDE_INSTALL_PREFIX="$HOME/gkide"
        # GKIDE build log
        - GKIDE_BUILD_LOG="${GKIDE_BUILD_DIR}/build.log"
        # Default CMake flags.
        - GKIDE_CMAKE_FLAGS="-DCMAKE_BUILD_TYPE=Debug
                             -DCMAKE_INSTALL_PREFIX:PATH=${GKIDE_INSTALL_PREFIX}
                             -DGKIDE_RELEASE_TYPE=dev
                             -DBUNDLED_DEPS_PREFIX:PATH=${DEPS_BUILD_DIR}/usr
                             -DTRAVIS_CI_ENABLE=OFF
                             -DNVIM_LOG_LEVEL_MIN=3"
        - DEPS_CMAKE_FLAGS="-DCMAKE_BUILD_TYPE=Release
                            -DDEPS_DOWNLOAD_DIR:PATH=$DEPS_DOWNLOAD_DIR"

matrix:
    include:
        - os: linux
          compiler: gcc
    fast_finish: true

install:        scripts/ci/install-deps.sh
before_script:  scripts/ci/build-prepare.sh
script:         scripts/ci/build-running.sh
after_success:  scripts/ci/build-success.sh

# for details see:
# - https://docs.travis-ci.com/user/for-beginners
# - https://docs.travis-ci.com/user/reference/overview/
# - https://docs.travis-ci.com/user/reference/trusty/
# - https://docs.travis-ci.com/user/environment-variables#Default-Environment-Variables
# - https://docs.travis-ci.com/user/customizing-the-build
