dist: trusty
sudo: required
language: cpp

git:
    depth: 100

# build only the master branch
branches:
    only:
        - master

cache:
    apt: true
    directories:
    - "${HOME}/.cache/gkide-deps"

notifications:
    email:
        on_success: never

env:
    global:
        # Encrypted environment variables
        # http://docs.travis-ci.com/user/encryption-keys/
        # GH_TOKEN="xxxx", for gkide-robot Github token
        # this is for autoupdate, skipped for pull request from others
        - secure: "OUDW9dSjFFg8gl/SbABuhKq1FAWL27OESKNqrUdYMTw8A9Yi++lG9wiwkdwbm6aBm0qvSQkh3UJsTUnTDgQH8mpl/OJCi/5yXqaoMftKpv+aAKFCN2JC/zAutBQ3NRU3NSzjlz2MTpEIO3xcrh+yVwkR4VfxFQ8N1zylSP/UMrZP6HsOud6rp8SFnN0sSmu+5HK0OaIXp8T2naIJI/xGhGkcvQJ86h3nGgn5zeATusmI/jyH3vVpCfoAuzW9hopRyWgOdwe8mNo+g2Mf6fgAruyt1z+IXFkBlOi64vqakXy78ngjdOYVCv2vZo+JceiLvbkVP6IYEu7VyuTURArTDMutAMsYiyJEt7iQqQ0PZMMJHgmQ3Gm5bgqz41VUP9rBwKGNQ0lTOBpZHujcftpQQFijNY141W0zbe+ZA/7zkcArWn9mv7ExE9qyYyeBS8NfjxoJ/prS+GbgDEr8VMqk2Kjq6ue0sMybCyeW0BM0uGQrd8gOGbqgz5fI5dFeuYgW1gcmR32NWnpDyhnIo9mhHFW2me5MCK/XyTnYaLmPjW+GjvtHSvnceiMpDpAz58Oeq6oRkRlSAkqlB8DZ8EJZx+VNq6RQyY4WqYXVcA2MjDMu9xl+5uydGoSiC9gS9orQU2qu10TvBjrYWZUAMKZCvqGgIW8OHKrEJ48cZoh1C7E="
        # Auto upload build log to 'autodocs/dev/log/...'
        - UPLOAD_BUILD_LOG=ON
        # Build log directory
        - BUILD_LOG_DIR="${HOME}/log"
        # Set 'OFF' to force rebuild of all dependencies
        - DEPS_CACHE_ENABLE=ON
        # The third-party dependency cache used by CI
        - DEPS_CACHE_DIR="${HOME}/.cache/gkide-deps"
        # If this file exists, the dependencies libraries cache is valid
        - DEPS_CACHE_MARKER="${HOME}/.cache/gkide-deps/.travis_cache_marker"
        # GKIDE build directory
        - GKIDE_BUILD_DIR="${TRAVIS_BUILD_DIR}/build"
        # GKIDE install perfix
        - GKIDE_INSTALL_PREFIX="${HOME}/gkide"

matrix:
    fast_finish: true
    include:
        - stage: normal
          os: linux
          compiler: gcc
          env: BUILD_NVIM_ONLY=ON
        - os: linux
          compiler: gcc
          env: USE_SHARED_QT5=ON
#       - os: linux
#         compiler: gcc
#         env: USE_SHARED_QT5=OFF
#       - os: osx
#         compiler: clang
#         env: USE_SHARED_QT5=OFF
#       - stage: release
#         os: linux
#         compiler: gcc
#         env: BUILD_NVIM_ONLY=ON
    allow_failures:
        - os: linux
          compiler: gcc
          env: USE_SHARED_QT5=ON

before_install: true
install:        scripts/ci/install-deps.sh
before_script:  scripts/ci/build-prepare.sh
script:         scripts/ci/build-running.sh
before_cache:   scripts/ci/build-cleanup.sh
after_success:  scripts/ci/build-success.sh
