/// @file snail/app/envdefs.h

#ifndef SNAIL_APP_ENVDEFS_H
#define SNAIL_APP_ENVDEFS_H

#define ENV_GKIDE_SNAIL_LOGGINGS  "GKIDE_SNAIL_LOGGINGS"
#define ENV_GKIDE_SNAIL_LOGLEVEL  "GKIDE_SNAIL_LOGLEVEL"
#define ENV_GKIDE_SNAIL_NVIMEXEC  "GKIDE_SNAIL_NVIMEXEC"
#define ENV_GKIDE_SNAIL_PLGSPATH  "GKIDE_SNAIL_PLGSPATH"

#endif // SNAIL_APP_ENVDEFS_H
