set(CPACK_PACKAGE_NAME    "${PROJECT_NAME}")
set(CPACK_PACKAGE_VENDOR  "gkide")
set(CPACK_TOPLEVEL_TAG    "${PROJECT_NAME}")

set(CPACK_PACKAGE_VERSION_MAJOR  ${SNAIL_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR  ${SNAIL_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH  ${SNAIL_VERSION_PATCH})

set(CPACK_PACKAGE_INSTALL_DIRECTORY    "${PROJECT_NAME}")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY  "${SNAIL_BRIEFDES}")

include(CPack)
